April/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.list, name='list'),
    path('create/', views.create, name='create'),

    path('like/<int:id>/', views.like, name='like'),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Post(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts")

posts/forms.py
from django import forms
from .models import Post

# Q2-1 : 모델폼정의

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.
def signup(request):
    # Q1-1 : 회원가입 GET
    # Q1-2 : 회원가입 POST
    pass

def login(request):
    if request.method=="POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("posts:list")
    else:
        form = AuthenticationForm()
    return render(request, "accounts/form.html", {"form":form})
    
def logout(request):
    auth_logout(request)
    return redirect("posts:list")

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Post
# Create your views here.

def list(request):
    posts = Post.objects.all()
    return render(request, 'posts/list.html', {'posts':posts})

@login_required
def create(request):
    # Q2-2 : 게시물작성 GET
    # Q2-3 : 게시물작성 POST
    pass

@login_required
def like(request, id):
    # Q3-1 : 좋아요 기능 구현
    pass

April/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
        <a href="{% url 'posts:create' %}">글쓰기</a>
        <a href="{% url 'accounts:logout' %}">로그아웃</a>
    {% else %}
        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

accounts/templates/accounts/form.html
{% extends 'base.html' %}

{% block body %}
    {% if request.resolver_match.url_name == 'signup' %}
        <h1>회원가입</h1>
    {% else %}
        <h1>로그인</h1>
    {% endif %}
    <form method='post'>
        {% csrf_token %} 
        {{form}}
        <input type="submit">
    </form>
{% endblock %}

posts/templates/posts/form.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% block body %}
    <h1>list</h1>
    {% for post in posts %}
        <h3>{{post.user.username}} : {{post.content}}</h3>
        <!-- Q3-3 : 좋아요 갯수출력 -->
        <p>명이 게시물을 좋아합니다.</p>
        <!-- Q3-2 : 좋아요 버튼추가 -->
    {% endfor %}
{% endblock %}